# docker-compose.yml
version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql  # Nombre del servicio de MySQL
      DB_USER: root
      DB_PASSWORD: smartstock
      DB_NAME: auth_db
      JWT_SECRET: "qwerty123"
    networks:
      - smartstock-net  # Misma red para ambos servicios
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: smartstock  # Contraseña root
      MYSQL_DATABASE: auth_db          # Nombre de la BD
    networks:
      - smartstock-net
    volumes:
      - mysql-data:/var/lib/mysql
    # Opcional: Healthcheck para esperar a que MySQL esté listo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:

networks:
  smartstock-net:
    driver: bridge