
services:
  # Servicios existentes
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: auth-db
      JWT_SECRET: "qwerty123qwerty123qwerty123qwerty123"
    networks:
      - smartstock-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      JWT_SECRET: "qwerty123qwerty123qwerty123qwerty123"
    networks:
      - smartstock-network

  # Nueva API de Análisis
  analytics-service:
    build: ./analytics-service
    ports:
      - "8082:8082"
    environment:
      MONGO_URI: "mongodb://analytics-db:27017"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: "us-east-1"
    depends_on:
      analytics-db:
        condition: service_healthy
    networks:
      - smartstock-network

  # Bases de datos
  auth-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: utec
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smartstock-network

  inventory-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: utec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartstock-network

  analytics-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - smartstock-network

volumes:
  mysql_data:
  postgres_data:
  mongo_data:

networks:
  smartstock-network:
    driver: bridge