services:
  db:
    image: mysql:8.0
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: utec          # Contraseña definida explícitamente
      MYSQL_DATABASE: bd_api_users       # Nombre de la base de datos
    ports:
      - "8005:3306"                      # Puerto mapeado: 8005 (host) → 3306 (contenedor)
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:                         # Healthcheck para esperar a que MySQL esté listo
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      db:
        condition: service_healthy       # Espera a que MySQL esté saludable
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db                        # Nombre del servicio de Docker (no IP)
      DB_USER: root
      DB_PASSWORD: utec
      DB_DATABASE: bd_api_users
      JWT_SECRET: your_jwt_secret_key    # Clave secreta para JWT
    networks:
      - app-network

    frontend:
      build: ./frontend
      container_name: auth-frontend
      depends_on:
        - backend
      ports:
        - "80:80"
      networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge